FROM iowarp/iowarp-user:latest

# g++ 13 isn't on ubuntu by default yet, needed for C++20
RUN apt-get update && apt-get install -y software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test -y \
    && apt-get update \
    && apt-get install -y gcc-13 g++-13 cmake ninja-build gdb git pkg-config build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

ENV SPACK_ROOT=/root/spack
RUN echo "source $SPACK_ROOT/share/spack/setup-env.sh" >> /etc/bash.bashrc

SHELL ["/bin/bash", "-c"]

RUN source $SPACK_ROOT/share/spack/setup-env.sh \
    && spack load hdf5 mpi

RUN echo "spack load hdf5 mpi iowarp" >> /etc/bash.bashrc

WORKDIR /project

CMD ["/bin/bash"]
