version: "3.8"
services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    image: iowarp-dev
    volumes:
      - .:/project
    working_dir: /project
    tty: true
    stdin_open: true
